// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfA6QtNGkf-CrZ9qTx1RMIEQpGv-6QsX0',
    appId: '1:194334679705:web:81f529ab3be20df12e0e08',
    messagingSenderId: '194334679705',
    projectId: 'chatting-app-e16e5',
    authDomain: 'chatting-app-e16e5.firebaseapp.com',
    storageBucket: 'chatting-app-e16e5.appspot.com',
    measurementId: 'G-8YMMEYKXEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDuYeNW-NIwIpY_kD_X1ONIfGwFCqKglQ',
    appId: '1:194334679705:android:b8a2be450d62fbd72e0e08',
    messagingSenderId: '194334679705',
    projectId: 'chatting-app-e16e5',
    storageBucket: 'chatting-app-e16e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJb4eaVgqbnVh5e9IsG-mSrjjJ1kKq-F4',
    appId: '1:194334679705:ios:50e47e49e44255372e0e08',
    messagingSenderId: '194334679705',
    projectId: 'chatting-app-e16e5',
    storageBucket: 'chatting-app-e16e5.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );
}
